//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersona_Familiar2
    {
        public string DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool Vive { get; set; }
        public bool ConVive { get; set; }
        public int IdPersonaPostulante { get; set; }
        public int IdFamiliar { get; set; }
        public int IdPersonaFamilia { get; set; }
        public int idParentesco { get; set; }
        public int IdSexo { get; set; }
        public string IdEstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string IdReligion { get; set; }
        public int idTipoNacionalidad { get; set; }
    }
}
