//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPostulante_Usuario_datos
    {
        public string Id { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public string Email { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public string ComoSeEntero { get; set; }
        public string Religion { get; set; }
        public string EstCivil { get; set; }
        public Nullable<System.DateTime> FechaCasamiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Nacionalidad { get; set; }
        public string DomDNI { get; set; }
        public string DOMAct { get; set; }
        public string Preferencia { get; set; }
        public string OficinaIncorp { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Etapa { get; set; }
        public string Estado { get; set; }
    }
}
