//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU.CPA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices", ConfigurationName="CPA.CleansingServicePortType")]
    public interface CleansingServicePortType {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exec", ReplyAction="urn:execResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SINU.CPA.execResponse exec(SINU.CPA.execRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:exec", ReplyAction="urn:execResponse")]
        System.Threading.Tasks.Task<SINU.CPA.execResponse> execAsync(SINU.CPA.execRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exec", WrapperNamespace="http://webservices", IsWrapped=true)]
    public partial class execRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xmlText;
        
        public execRequest() {
        }
        
        public execRequest(string authKey, string xmlText) {
            this.authKey = authKey;
            this.xmlText = xmlText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execResponse", WrapperNamespace="http://webservices", IsWrapped=true)]
    public partial class execResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public execResponse() {
        }
        
        public execResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CleansingServicePortTypeChannel : SINU.CPA.CleansingServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CleansingServicePortTypeClient : System.ServiceModel.ClientBase<SINU.CPA.CleansingServicePortType>, SINU.CPA.CleansingServicePortType {
        
        public CleansingServicePortTypeClient() {
        }
        
        public CleansingServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CleansingServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CleansingServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CleansingServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SINU.CPA.execResponse SINU.CPA.CleansingServicePortType.exec(SINU.CPA.execRequest request) {
            return base.Channel.exec(request);
        }
        
        public string exec(string authKey, string xmlText) {
            SINU.CPA.execRequest inValue = new SINU.CPA.execRequest();
            inValue.authKey = authKey;
            inValue.xmlText = xmlText;
            SINU.CPA.execResponse retVal = ((SINU.CPA.CleansingServicePortType)(this)).exec(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SINU.CPA.execResponse> SINU.CPA.CleansingServicePortType.execAsync(SINU.CPA.execRequest request) {
            return base.Channel.execAsync(request);
        }
        
        public System.Threading.Tasks.Task<SINU.CPA.execResponse> execAsync(string authKey, string xmlText) {
            SINU.CPA.execRequest inValue = new SINU.CPA.execRequest();
            inValue.authKey = authKey;
            inValue.xmlText = xmlText;
            return ((SINU.CPA.CleansingServicePortType)(this)).execAsync(inValue);
        }
    }
}
